# Generated by Django 4.2.2 on 2023-08-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество этажей'),
        ),
        migrations.AddField(
            model_name='house',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Проект'),
        ),
    ]
