# Generated by Django 4.2.2 on 2023-08-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_house_floor_house_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='building_type',
            field=models.CharField(blank=True, choices=[('Сруб', 'Сруб'), ('Кирпичные дома', 'Кирпичные дома'), ('Каркасные дома', 'Каркасные дома')], max_length=100, null=True, verbose_name='Тип постройки'),
        ),
    ]
