# Generated by Django 4.2.2 on 2023-08-09 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('catalog', '0003_alter_house_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_img', to='wagtailimages.image'),
        ),
    ]
